// Generated by CoffeeScript 2.0.1
var config, db, hero, heroes, heroesDB, i, len;

import Firebase from 'firebase';

config = {
  apiKey: "AIzaSyArjuH0N-SAIwgd8DzZN7dvTxsrPIoiQVo",
  authDomain: "myfirstfirebase-230fb.firebaseapp.com",
  databaseURL: "https://myfirstfirebase-230fb.firebaseio.com",
  projectId: "myfirstfirebase-230fb",
  storageBucket: "myfirstfirebase-230fb.appspot.com",
  messagingSenderId: "147999552069"
};

firebase.initializeApp(config);

db = firebase.database();

heroesDB = db.ref("/heroes");

heroes = [
  {
    name: '勇者ブルー',
    bgColor: '#0074bf',
    selected: true
  },
  {
    name: '勇者レッド',
    bgColor: '#c93a40',
    selected: true
  },
  {
    name: '勇者グリーン',
    bgColor: '#56a764',
    selected: true
  },
  {
    name: '勇者イエロー',
    bgColor: '#f2cf01',
    selected: true
  },
  {
    name: '勇者ホワイト',
    bgColor: '#fff',
    selected: true
  },
  {
    name: '勇者ブラック',
    bgColor: '#222',
    selected: true
  }
];

for (i = 0, len = heroes.length; i < len; i++) {
  hero = heroes[i];
  heroesDB.set(hero);
}
